# Sử dụng base image Python 3.10
FROM python:3.10-slim-bullseye

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Biến môi trường giúp Python in log ra terminal ngay lập tức (không bị buffer)
ENV PYTHONUNBUFFERED=1
ENV AIRFLOW_HOME=/opt/airflow

# Cài đặt các gói hệ thống cơ bản cần thiết (Playwright + thư viện build psycopg2)
RUN apt-get update && apt-get install -y \
    wget curl gnupg libgomp1 libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy file requirements vào container
COPY requirements.txt .

# 1. Cài đặt PyTorch chuẩn CPU
RUN pip install --no-cache-dir torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

# 2. Cài đặt các thư viện trong requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# 3. Cài đặt thêm các thư viện ML/VectorDB
RUN pip install --no-cache-dir scikit-learn==1.4.1.post1 chromadb==0.4.24 sentence-transformers==2.5.1 pysqlite3-binary

# 4. Cài đặt Apache Airflow chuẩn ràng buộc Constraints từ Apache
RUN pip install --no-cache-dir "apache-airflow==2.8.1" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-3.10.txt" \
    && pip install --no-cache-dir psycopg2-binary

# 5. Cài đặt trình duyệt cho Playwright
RUN playwright install --with-deps chromium

# Copy toàn bộ mã nguồn vào thư mục /app trong container
COPY . .